name: Compile and create release
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        env:
          USER: ''
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = false
            substituters = https://nix-community.cachix.org https://cache.nixos.org
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run test
        run: nix-shell --run "dotnet test"